# Generated by Django 4.2.7 on 2023-11-06 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipestep',
            old_name='Recipe',
            new_name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='recipe.category')),
                ('recipe', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe')),
            ],
        ),
    ]
