# Generated by Django 4.2.7 on 2023-11-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_alter_ingredient_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='quantity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='content',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='title',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
