# Generated by Django 4.2.7 on 2023-11-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_rename_recipe_recipestep_recipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipestep',
            name='title',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
