# Generated by Django 4.2.7 on 2023-11-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_recipestep_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipestep',
            name='title',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
