# Generated by Django 4.2.7 on 2023-11-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_alter_recipe_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='special',
            field=models.BooleanField(default=True),
        ),
    ]
